###############################################################
#  Generated by:      Cadence Encounter 13.10-p003_1
#  OS:                Linux x86_64(Host ID bluestar)
#  Generated on:      Mon Jun  2 11:54:42 2014
#  Design:            fpu
#  Command:           floorPlan -site FreePDK45_38x28_10R_NP_162NW_34O -r 1 ...
###############################################################

Version: 8

Head Box: 0.0000 0.0000 317.8050 315.0000
IO Box: 0.0000 0.0000 317.8050 315.0000
Core Box: 0.0000 0.0000 317.8050 315.0000
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: FreePDK45_38x28_10R_NP_162NW_34O 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_0 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 0.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_1 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 1.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_2 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 2.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_3 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 4.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_4 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 5.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_5 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 7.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_6 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 8.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_7 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 9.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_8 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 11.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_9 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 12.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_10 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 14.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_11 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 15.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_12 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 16.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_13 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 18.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_14 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 19.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_15 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 21.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_16 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 22.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_17 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 23.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_18 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 25.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_19 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 26.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_20 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 28.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_21 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 29.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_22 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 30.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_23 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 32.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_24 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 33.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_25 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 35.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_26 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 36.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_27 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 37.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_28 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 39.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_29 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 40.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_30 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 42.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_31 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 43.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_32 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 44.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_33 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 46.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_34 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 47.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_35 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 49.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_36 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 50.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_37 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 51.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_38 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 53.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_39 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 54.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_40 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 56.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_41 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 57.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_42 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 58.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_43 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 60.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_44 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 61.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_45 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 63.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_46 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 64.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_47 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 65.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_48 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 67.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_49 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 68.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_50 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 70.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_51 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 71.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_52 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 72.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_53 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 74.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_54 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 75.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_55 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 77.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_56 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 78.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_57 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 79.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_58 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 81.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_59 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 82.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_60 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 84.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_61 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 85.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_62 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 86.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_63 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 88.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_64 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 89.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_65 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 91.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_66 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 92.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_67 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 93.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_68 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 95.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_69 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 96.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_70 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 98.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_71 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 99.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_72 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 100.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_73 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 102.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_74 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 103.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_75 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 105.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_76 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 106.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_77 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 107.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_78 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 109.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_79 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 110.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_80 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 112.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_81 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 113.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_82 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 114.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_83 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 116.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_84 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 117.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_85 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 119.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_86 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 120.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_87 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 121.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_88 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 123.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_89 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 124.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_90 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 126.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_91 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 127.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_92 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 128.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_93 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 130.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_94 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 131.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_95 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 133.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_96 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 134.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_97 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 135.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_98 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 137.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_99 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 138.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_100 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 140.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_101 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 141.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_102 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 142.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_103 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 144.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_104 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 145.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_105 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 147.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_106 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 148.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_107 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 149.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_108 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 151.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_109 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 152.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_110 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 154.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_111 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 155.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_112 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 156.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_113 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 158.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_114 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 159.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_115 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 161.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_116 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 162.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_117 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 163.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_118 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 165.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_119 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 166.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_120 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 168.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_121 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 169.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_122 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 170.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_123 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 172.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_124 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 173.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_125 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 175.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_126 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 176.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_127 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 177.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_128 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 179.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_129 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 180.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_130 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 182.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_131 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 183.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_132 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 184.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_133 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 186.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_134 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 187.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_135 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 189.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_136 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 190.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_137 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 191.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_138 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 193.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_139 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 194.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_140 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 196.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_141 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 197.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_142 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 198.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_143 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 200.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_144 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 201.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_145 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 203.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_146 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 204.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_147 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 205.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_148 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 207.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_149 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 208.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_150 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 210.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_151 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 211.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_152 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 212.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_153 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 214.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_154 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 215.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_155 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 217.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_156 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 218.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_157 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 219.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_158 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 221.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_159 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 222.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_160 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 224.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_161 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 225.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_162 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 226.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_163 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 228.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_164 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 229.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_165 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 231.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_166 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 232.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_167 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 233.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_168 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 235.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_169 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 236.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_170 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 238.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_171 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 239.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_172 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 240.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_173 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 242.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_174 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 243.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_175 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 245.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_176 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 246.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_177 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 247.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_178 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 249.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_179 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 250.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_180 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 252.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_181 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 253.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_182 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 254.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_183 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 256.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_184 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 257.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_185 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 259.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_186 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 260.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_187 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 261.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_188 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 263.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_189 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 264.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_190 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 266.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_191 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 267.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_192 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 268.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_193 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 270.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_194 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 271.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_195 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 273.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_196 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 274.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_197 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 275.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_198 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 277.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_199 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 278.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_200 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 280.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_201 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 281.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_202 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 282.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_203 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 284.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_204 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 285.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_205 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 287.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_206 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 288.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_207 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 289.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_208 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 291.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_209 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 292.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_210 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 294.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_211 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 295.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_212 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 296.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_213 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 298.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_214 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 299.6000 FS 1672 1 0.1900 0.0000
DefRow: ROW_215 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 301.0000 N 1672 1 0.1900 0.0000
DefRow: ROW_216 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 302.4000 FS 1672 1 0.1900 0.0000
DefRow: ROW_217 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 303.8000 N 1672 1 0.1900 0.0000
DefRow: ROW_218 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 305.2000 FS 1672 1 0.1900 0.0000
DefRow: ROW_219 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 306.6000 N 1672 1 0.1900 0.0000
DefRow: ROW_220 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 308.0000 FS 1672 1 0.1900 0.0000
DefRow: ROW_221 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 309.4000 N 1672 1 0.1900 0.0000
DefRow: ROW_222 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 310.8000 FS 1672 1 0.1900 0.0000
DefRow: ROW_223 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 312.2000 N 1672 1 0.1900 0.0000
DefRow: ROW_224 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 313.6000 FS 1672 1 0.1900 0.0000

######################################################
#  Track: dir start number space layer_num layer1 ...#
######################################################
Track: Y 1.6700 196 1.6000 1 10
Track: X 1.7750 189 1.6800 1 10
Track: X 0.9350 378 0.8400 1 9
Track: Y 1.6700 196 1.6000 1 9
Track: Y 0.9100 374 0.8400 1 8
Track: X 0.9350 378 0.8400 1 8
Track: X 0.3750 1134 0.2800 1 7
Track: Y 0.9100 374 0.8400 1 7
Track: Y 0.3500 1124 0.2800 1 6
Track: X 0.3750 1134 0.2800 1 6
Track: X 0.3750 1134 0.2800 1 5
Track: Y 0.3500 1124 0.2800 1 5
Track: Y 0.0700 2250 0.1400 1 4
Track: X 0.3750 1134 0.2800 1 4
Track: X 0.0950 1673 0.1900 1 3
Track: Y 0.0700 2250 0.1400 1 3
Track: Y 0.0700 2250 0.1400 1 2
Track: X 0.0950 1673 0.1900 1 2
Track: X 0.0950 1673 0.1900 1 1
Track: Y 0.0700 2250 0.1400 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: X 317.3950 2 0.4100
GCellGrid: X 0.0950 168 1.9000
GCellGrid: X 0.0000 2 0.0950
GCellGrid: Y 313.6700 2 1.3300
GCellGrid: Y 0.0700 225 1.4000
GCellGrid: Y 0.0000 2 0.0700

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

###############################1p########################
#  <SelectiveBlockage>                                #
#     <cell name="cell_name" />                     #
#  </SelectiveBlockage                                #
#######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#######################################################################################
#  <Blackboxes>                                                                       #
#     <Blackbox  cell=name  width=N height=N                                          #
#                { area=A | gatecount=N areaPerGate=A cellUtil=F |                    #
#                  gateArea=F {macroArea=F | macorList='str'} includeMacroArea={0|1}} #
#                [minWidth=N | minHeight=N | fixedWidh=N | fixedHeight=N]             #
#                [aspectRatio=R] >                                                    #
#         <Box llx=float lly=float urx=float ury=float /> ...                         #
#     </Blackbox>                                                                     #
#  </Blackboxes>                                                                      #
#######################################################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: VDD -pwr
PhysicalNet: VSS -gnd

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################
###########################################################################
#  <HierarchicalPartitions>                                               #
#     <GlobalPinConstraints>                                              #
#         <PinSpacing spacing=val />                                      #
#         <PinWidth layer=layerId width=val />                            #
#         <PinDepth layer=layerId depth=val />                            #
#         <CornerToPinDistance distance=val />                            #
#     </GlobalPinConstraints>                                             #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val     #
#         isAltLayer=val isPffGroup=val isSpreadPin=val                   #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val >#
#         <Net name="net_name" /> ...                                     #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval                 #
#         coreToBottom=val pinSpacingNorth=val pinSpacingWest=val         #
#         pinSpacingSouth=val pinSpacingEast=val  blockedLayers=xval >    #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <PinToCornerDistance  totalCorners=nrCorners >                  #
#            <Corner number=<cornerNumber> distance=<distance> /> ...     #
#         </PinToCornerDistance >                                         #
#         <PinSpacingArea llx=val lly=val urx=val ury=val spacing=val />  #
#         <LayerWidthDepth layer=layerId width=w depth=d />               #
#         <PinConstraint>                                                 #
#            <Pin name="pinName" >                                      #
#               <edge edgeNumber=val />                                   #
#               <spacing space=val />                                    #
#               <layer layerMap=xval />                                  #
#               <pinWidth width=val />                                   #
#               <pinDepth depth=val />                                   #
#               <location x=val y=val />                                 #
#            </Pin>                                                       #
#         </PinConstraint>                                                #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name" pins=nr            #
#         spacing=val isOptOrder=val isAltLayer=val isSpreadPin=val       #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val >#
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num layerPriority=val cell="name" >     #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <GlobalPinConstraints>
        <PinSpacing spacing=2 />
        <CornerToPinDistance distance=5 />
    </GlobalPinConstraints>
    <Partition name="fpu" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=-1 pinSpacingWest=-1 pinSpacingSouth=-1 pinSpacingEast=-1 blockedLayers=0x3ff >
	<PinLayer side="N" Metal2=yes Metal4=yes Metal6=yes Metal8=yes Metal10=yes />
	<PinLayer side="W" Metal3=yes Metal5=yes Metal7=yes Metal9=yes />
	<PinLayer side="S" Metal2=yes Metal4=yes Metal6=yes Metal8=yes Metal10=yes />
	<PinLayer side="E" Metal3=yes Metal5=yes Metal7=yes Metal9=yes />
    <PinToCornerDistance totalCorners=4 >
      <Corner number=0 distance=-1 />
      <Corner number=1 distance=-1 />
      <Corner number=2 distance=-1 />
      <Corner number=3 distance=-1 />
    </PinToCornerDistance>
    </Partition>
</HierarchicalPartitions>

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

#################################################################
#  <PlacementBlockages>                                         #
#     <Blockage name="blk_name" type="hard|soft|partial">       #
#       <Attr density=1.2 inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </PlacementBlockages>                                        #
#################################################################

#################################################################
#  <SizeBlockages>                                             #
#     <Blockage name="blk_name">                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </SizeBlockages>                                            #
#################################################################

###########################################################################
#  <RouteBlockages>                                                       #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">   #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes />   #
#       <Layer type="route|cut|masterslice" id=layerNo />                 #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                       #
#     </Blockage>                                                         #
#  </RouteBlockages>                                                      #
###########################################################################

######################################################
#  PrerouteAsObstruct: <layer_treated_as_obstruct>   #
######################################################
PrerouteAsObstruct: 0x3

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: .fpu3644.rs.fp.spr

##############################################################################
#  <IOPins>                                                                  #
#    <Pin name="pin_name" type="clock|power|ground|analog"                   #
#         status="covered|fixed|placed" is_special=1 >                       #
#      <Port>                                                                #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d orientation=val /> #
#        <Via name="via_name" x=1 y=2 />...                                  #
#        <Layer id=id spacing=1.2 drw=1.2>                                   #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />              #
#        </Layer> ...                                                        #
#      </Port>  ...                                                          #
#      <Antenna model=num type="name" value=float_num layer=num /> ...       #
#    </Pin> ...                                                              #
#  </IOPins>                                                                 #
##############################################################################


#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="fpu">
  </Design>
</Properties>

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
