set log file fv/fpu/rtl_to_g1_withoutovf.log -replace
// Generated by Cadence Encounter(R) RTL Compiler v12.10-s012_1
tclmode
set env(RC_VERSION) "v12.10-s012_1"
vpxmode
set dofile abort exit
usage -auto -elapse
// tclmode
// set env(CDN_SYNTH_ROOT) /data/software/cadence/installs/EDI131/tools.lnx86
// vpxmode
tclmode
set ver [lindex [split [lindex [get_version_info] 0] "-"] 0]
if {$ver >= 08.10} {
  vpx set naming style rc
}
vpxmode
set naming rule "%s[%d]" -instance_array
set naming rule "%s_reg" -register -golden
set naming rule "%L.%s" "%L[%d].%s" "%s" -instance
set naming rule "%L.%s" "%L[%d].%s" "%s" -variable
set undefined cell black_box -noascend -both
set undriven signal Z -golden

add search path -library /data/research/encounter/ASIC_project/NangateOpenCellLibrary/Front_End/Liberty /data/research/encounter/ASIC_project/NangateOpenCellLibrary/Front_End/Liberty/ECSM /data/research/encounter/ASIC_project/NangateOpenCellLibrary/Back_End/lef
read library -statetable -liberty -both  \
	NangateOpenCellLibrary_typical_ecsm.lib

add search path -design /data/research/encounter/ASIC_project/design/rtl /data/research/encounter/ASIC_project/design/include /data/research/encounter/ASIC_project/design/lib /data/research/encounter/ASIC_project/design/common /data/research/encounter/ASIC_project/design/srams /data/research/encounter/ASIC_project/design/pr_macro
read design  -verilog -define SYNTHESIS  -golden -lastmod -noelab \
	/data/research/encounter/ASIC_project/design/common/cluster_header.v \
	/data/research/encounter/ASIC_project/design/rtl/swrvr_clib.v \
	/data/research/encounter/ASIC_project/design/common/swrvr_dlib.v \
	/data/research/encounter/ASIC_project/design/common/synchronizer_asr.v \
	/data/research/encounter/ASIC_project/design/rtl/bw_clk_cl_fpu_cmp.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_add_ctl.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_add_exp_dp.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_add_frac_dp.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_add.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_cnt_lead0_53b.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_cnt_lead0_64b.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_cnt_lead0_lvl1.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_cnt_lead0_lvl2.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_cnt_lead0_lvl3.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_cnt_lead0_lvl4.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_denorm_3b.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_denorm_3to1.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_denorm_frac.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_div_ctl.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_div_exp_dp.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_div_frac_dp.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_div.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_in2_gt_in1_2b.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_in2_gt_in1_3b.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_in2_gt_in1_3to1.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_in2_gt_in1_frac.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_in_ctl.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_in_dp.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_in.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_mul_ctl.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_mul_exp_dp.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_mul_frac_dp.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_mul.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_out_ctl.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_out_dp.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_out.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_rptr_groups.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_rptr_macros.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu_rptr_min_global.v \
	/data/research/encounter/ASIC_project/design/pr_macro/mul64.v \
	/data/research/encounter/ASIC_project/design/common/test_stub_scan.v \
	/data/research/encounter/ASIC_project/design/srams/bw_r_rf16x160.v \
	/data/research/encounter/ASIC_project/design/rtl/fpu.v

elaborate design -golden -root fpu -rootonly

read design -verilog -revised -lastmod -noelab \
	-unzip fv/fpu/g1.v.gz

elaborate design -revised -root fpu

substitute blackbox model -golden
report design data
report black box

uniquify -all -nolib
set flatten model -seq_constant -seq_constant_x_to 0
set flatten model -nodff_to_dlat_zero -nodff_to_dlat_feedback
// set parallel option -threads 4 -license xl -norelease_license
// set compare options -threads 0
set analyze option -auto

write hier_compare dofile fv/fpu/hier_rtl_to_g1_withoutovf.do \
	-noexact_pin_match -constraint -usage -replace -balanced_extraction -input_output_pin_equivalence \
	-prepend_string "analyze datapath -module -verbose; usage; analyze datapath -verbose"
run hier_compare fv/fpu/hier_rtl_to_g1_withoutovf.do -analyze_abort  -dynamic_hierarchy
// report hier_compare result -dynamicflattened
set system mode lec
tclmode
puts "No of diff points    = [get_compare_points -diff -count]"
if {[get_compare_points -diff -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
#     foreach i [get_compare_points -diff] {
#         vpx report test vector [get_keypoint $i]
#         puts "     ----------------------------"
#     }
}
vpxmode
exit -force
